### ISSUE TITLE
Mass Assignment app not working (code doesn't exist)

### ISSUE THREAD

**Issue by adamczi** [duo-labs/appsec-education#2]
Hi, I tried to run first lab - Python AppSec Mass Assignment, but the Flask application in lab does not start. The issue is application code doesn't get copied to the server, and boot script reports:

```
~/web$ boot
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
App is booting... 
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/home/whitehat/boot.sh: line 10: cd: /home/whitehat/web: No such file or directory
Traceback (most recent call last):
  File "/home/whitehat/venvs/env/lib/python3.5/site-packages/gunicorn/util.py", line 436, in getcwd
    a = os.stat(os.environ['PWD'])
FileNotFoundError: [Errno 2] No such file or directory: '/home/whitehat/web'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/whitehat/venvs/env/bin/gunicorn", line 5, in <module>
    from gunicorn.app.wsgiapp import run
  File "/home/whitehat/venvs/env/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "/home/whitehat/venvs/env/lib/python3.5/site-packages/gunicorn/app/base.py", line 13, in <module>
    from gunicorn.config import Config, get_default_config_file
  File "/home/whitehat/venvs/env/lib/python3.5/site-packages/gunicorn/config.py", line 1003, in <module>
    class Chdir(Setting):
  File "/home/whitehat/venvs/env/lib/python3.5/site-packages/gunicorn/config.py", line 1008, in Chdir
    default = util.getcwd()
  File "/home/whitehat/venvs/env/lib/python3.5/site-packages/gunicorn/util.py", line 443, in getcwd
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
Gunicorn failed to start

View /home/whitehat/error.log for details.
```

Indeed `~/web` dir is empty:
```
~/web$ ls -la .
total 0
```

URL of the lab is: https://community.hunter2.com/lesson/duo-mass-assignment?module=duo-security-python-appsec

**Comment by adamczi** [comment]
Tried the next Python lab: The Power of None, with the same result - no code for me. Though React lab (React string sanitization) seems to work.

**Comment by ccornutt-duo** [comment]
Hi there @adamczi - sorry to hear you're having trouble with these labs. As they were designed to work with the Hunter2 platform (now Veracode Security Labs) and not in a general Docker environment, there might be some issues just running them outside of that platform. 

That said, you shouldn't _need_ to run that `boot` command to get the web server started up. I believe it should just be running when you bring up the docker container. Could you check and see if this is the case? I believe it defaults to `localhost:5000`.

**Comment by adamczi** [comment]
Hi @ccornutt-duo , thanks for your answer, but I actually am running it online at https://community.hunter2.com, not on a local Docker container. Is that what you mean? The `boot` command runs automatically at the terminal on the website, my only input was `ls -la .`.

**Comment by ccornutt-duo** [comment]
Ahh, okay - try using this to see if it clears it up:

`cd ..; cd web; boot;`

There's a known issue with how the instance is set up on the platform that we're working on that could be causing this. Sorry for the trouble!

**Comment by adamczi** [comment]
Hi, after doing `cd ..` I'm not able to get back into `web` anymore. It is not listed:

```
~/web$ cd ..
~$ cd web
bash: cd: web: No such file or directory
~$ ls -la
total 52
drwxr-xr-x 1 whitehat whitehat 4096 Mar 13 13:39 .
drwxr-xr-x 1 root     root     4096 Feb 14 18:05 ..
-rw-r--r-- 1 whitehat whitehat  220 May 15  2017 .bash_logout
-rw-r--r-- 1 whitehat whitehat 3652 Feb 14 18:06 .bashrc
-rw-r--r-- 1 whitehat whitehat  675 May 15  2017 .profile
-rw-rw-r-- 1 whitehat whitehat  106 Feb 14 16:33 .vimrc
-rwxrwxr-x 1 whitehat whitehat  920 Mar 13 13:39 boot.sh
-rwxrwxr-x 1 whitehat whitehat 2033 Feb 14 18:03 boot_lib.sh
-rw-r--r-- 1 whitehat whitehat   49 Mar 13 13:39 error.log
drwxr-xr-x 1 whitehat whitehat 4096 Feb 14 18:07 venvs
```

nor I can access it using `cd -`:
```
~$ cd -
bash: cd: /home/whitehat/web: No such file or directory
```

Although I'm able to create this directory, any `boot` script won't work since there is no code inside that directory (so error.log reports `ImportError: No module named 'app'`).

**Comment by ccornutt-duo** [comment]
Hi @adamczi, sorry for the delay getting back with you on this. I spoke with the Hunter2 folks and I think we've solved this issue. Would you mind giving it a try again and see if it cooperates?

**Comment by adamczi** [comment]
Hi, I checked quickly the lab and it's web endpoint and they both seem to work. Thanks a lot!
